export type CurrencyCode = 'USD' | 'BYN' | 'RUB'

export interface ExchangeRates {
  USD: number
  BYN: number
  RUB: number
  lastUpdated: Date
}

export interface CategoryConfig {
  name: string
  color: string
  icon: string
  isDefault?: boolean
}

export type CategoryKey = string

export interface Category {
  [key: CategoryKey]: number
}

export type { Atm } from './atm'

export interface CustomCategoryBudget {
  id: string
  name: string
  emoji: string
  color: string
  percentage: number
  amount: number
}

export interface BudgetData {
  salary: number
  savingsGoal: number
  categories: Category
  remainingAmount: number
  remainingPercent: number
  customCategories?: CustomCategoryBudget[]
}

export interface MonthlyExpense {
  id: string
  month: string
  category: string
  amount: number
  description: string
  date: string
  currency?: CurrencyCode  // валюта расхода
  isBudgeted?: boolean    // true если это запланированный расход из бюджета
  isAutoGenerated?: boolean // true если создан автоматически при наступлении месяца
}

export interface MonthlyStats {
  month: string
  totalSpent: number
  byCategory: Partial<Category>
  remaining: number
}

export const defaultCategories: Record<string, CategoryConfig> = {
  savings: { name: 'Сбережения', color: '#10b981', icon: '💰', isDefault: true },
  food: { name: 'Еда', color: '#f59e0b', icon: '🍽️', isDefault: true },
  clothing: { name: 'Одежда', color: '#8b5cf6', icon: '👔', isDefault: true },
  entertainment: { name: 'Развлечения', color: '#ec4899', icon: '🎮', isDefault: true },
  transport: { name: 'Транспорт', color: '#3b82f6', icon: '🚗', isDefault: true },
  utilities: { name: 'Коммунальные услуги', color: '#06b6d4', icon: '💡', isDefault: true },
  health: { name: 'Здоровье', color: '#ef4444', icon: '🏥', isDefault: true },
  other: { name: 'Прочее', color: '#6b7280', icon: '📦', isDefault: true },
}

export const defaultPercentages: Category = {
  savings: 20,
  food: 25,
  clothing: 8,
  entertainment: 10,
  transport: 12,
  utilities: 15,
  health: 5,
  other: 5,
}

export const STORAGE_KEYS = {
  BUDGET: 'moneyManagementBudget',
  EXPENSES: 'moneyManagementExpenses',
  SETTINGS: 'moneyManagementSettings',
  CATEGORIES: 'moneyManagementCategories',
  CUSTOM_CATEGORIES: 'moneyManagementCustomCategories',
  LAST_BUDGETED_MONTH: 'moneyManagementLastBudgetedMonth',
} as const

// Legacy mappings for backward compatibility with existing components
export const categoryNames: Record<string, string> = Object.fromEntries(
  Object.entries(defaultCategories).map(([key, config]) => [key, config.name])
)

export const categoryColors: Record<string, string> = Object.fromEntries(
  Object.entries(defaultCategories).map(([key, config]) => [key, config.color])
)

export interface CustomCategory {
  id: string
  name: string
  emoji: string
  color: string
  percentage: number
}
